logger:
  file:
    level: DEBUG
    sink: ./logs/{time:YYYY-MM-DD}/log_{time:HH_mm_ss}.log
    format: <green>{time:YYYY-MM-DD HH:mm:ss}</green>[<level>{level}</level>]<level>{message}</level>
    rotation: "5 MB"
    retention: "1 days"

  errorFile:
    level: ERROR
    sink: ./logs/{time:YYYY-MM-DD}/error.log
    format: <green>{time:YYYY-MM-DD HH:mm:ss}</green>[<level>{level}</level>]<level>{message}</level>
    rotation: "5 MB"
    retention: "1 days"

  console:
    level: DEBUG
    format: <green>{time:YYYY-MM-DD HH:mm:ss}</green>[<level>{level}</level>]<level>{message}</level>

mysql:
  # mysql数据库服务器地址和端口号
  host: 127.0.0.1
  port: 3306
  # 用户名和密码
  user: root
  password: "111111"
  # 数据库名
  db: test_db

email:
  # 开启发送邮件
  flag: false
  # 邮件服务器地址和端口号
  smtp_server: smtp.163.com
  port: 25
  # 发件人地址
  from_addr: your email address
  # 收件人地址
  to_addr: receive email address
  # 发件人邮箱的用户名和密码
  username: your username
  password: your password
  # 邮件主题
  subject: ddddpytest测试报告
  # 用例执行通过文本
  success_text: 测试用例全部执行通过了
  # 用例执行失败文本
  failed_text: 测试用例执行失败了